[package]
name = "llmc"
version = "0.1.1"
edition = "2021"

[dependencies]
ureq = { version = "2", features = ["json"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
